export class EventoMusica{
    id:number;
    nombreEvento:String;
    ubicacion:String;
    ubicacionDetalle:String;
    ubicacionReferencia:String;
    distrito:String;
    region:String;
    fechaYHoraInicio:Date;
    fechaYHoraInicioAlternativa:Date;
    fechaYHoraFin:Date;
    descripcion:String;
    precio:number;
    organizador:String;
    cantidadAsistere:number;
    cantidadInteresados:number;
    cantidadCompartidos:number;
    valoracionGeneral:number;
    imagen:String;
    enlace:String;
}